# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

before_install:
  - cd R-package

cache: packages

after_success:
  - cd R-package
  - Rscript -e 'covr::codecov()'
