matrix:
  include:
    - language: R
      before_install:
        - cd R-package
      cache: packages
      after_success:
        - travis_wait 40 Rscript -e 'covr::codecov(path = ".", quiet = FALSE, type = c("vignettes", "examples", "tests"))'

    - dist: xenial
      language: python
      python:
        - "3.7"

      addons:
        apt:
          packages:
            - swig

      # command to install dependencies
      install:
        - pip install -r ./python/requirements.txt
        - pip install pytest
        - pip install pytest-cov
        - pip install scikit-learn
        - python ./python/setup.py install

      # command to run tests
      script:  
        - pytest python/ --cov=./ --cov-report=xml
        
      after_success:
        - codecov # run codecov


