# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

before_install:
  - cd R-package

cache: packages

after_success:
  - travis_wait 40 Rscript -e 'covr::codecov(path = ".", quiet = FALSE, type = c("vignettes", "examples", "tests"))'
