
name: ABESS-CI

on:
  push:
    branches:
      - main
      - master


jobs:
  InstallUb:
    name: Installation test on Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install -y swig bash mingw-w64
        pip install -r ./python/requirements.txt
    - name: Install abess
      run: |
        python ./python/setup.py install
        
  InstallWins:
    name: Installation test on Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        choco install swig mingw git
        pip install -r ./python/requirements.txt
    - name: Install abess
      run: |
        python ./python/setup.py install
        

  pkgdown:
    name: pkgdown
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.ABESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps("R-package", dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps("R-package", dependencies = TRUE)
          install.packages("pkgdown", type = "binary")
          install.packages("survival", type = "binary")
          install.packages("Hmisc", type = "binary")
          install.packages("ROCR", type = "binary")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL R-package

      - name: Deploy package
        run: |
          git config --local user.email "zhuj37@mail2.sysu.edu.cn"
          git config --local user.name "Mamba413"
          Rscript -e 'pkgdown::deploy_to_branch("R-package", new_process = FALSE)'
  
  codecovPy:
    name: Codecov workflow for Python-package
    runs-on: ubuntu-18.04
    env:
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install -r ./python/requirements.txt
        pip install pytest
        pip install pytest-cov
        pip install scikit-learn
        pip install lifelines
        pip install pandas
        pip install codecov
        pip install gcovr
        export CFLAGS="--coverage"
        python ./python/setup.py install
        ls *
        pytest ./python --cov=abess --cov-report=xml
        gcovr ./python/src/ --xml 
        ls *
        codecov -F Python

  codecovR:
    name: Codecov for R-package
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Ubuntu dependencies
        run: |
          sudo apt-get install libxml2-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install python3
          sudo apt-get install  python3-pip

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps("R-package", dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          remotes::install_deps("R-package", dependencies = TRUE)
          install.packages("covr")
          install.packages("xml2")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL R-package

      - name: Generate coverage report
        run: |
          Rscript -e 'library(covr); x <- package_coverage(path = "./R-package", quiet = FALSE, type = c("vignettes", "examples", "tests"), function_exclusions = "\\.onUnload"); to_cobertura(x, "rpackage.xml")'

      - name: Upload coverage report
        run: |
          pip install --upgrade pip
          pip3 install --user codecov
          codecov -F rpackage -f rpackage.xml

  
