name: R Build

on:
  push:
    paths:
      - 'R-package/**'
      - 'src/**'
      - '.github/workflows/r_test.yml'
      - '!R-package/.gitignore'
      - '!R-package/cran-comments.md'
      - '!R-package/pre-release.R'
      - '!R-package/data-raw/**'
    branches:
      - master
  pull_request:
    paths:
      - 'R-package/**'
      - 'src/**'
      - '.github/workflows/r_test.yml'
      - '!R-package/.gitignore'
      - '!R-package/cran-comments.md'
      - '!R-package/pre-release.R'
      - '!R-package/data-raw/**'
    branches:
      - master

jobs:
  Install-Test:
    name: Installation test for R-package
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          install.packages('devtools')
          saveRDS(remotes::dev_package_deps("R-package", dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Install dependencies
        working-directory: ./R-package
        run: |
          print(getwd())
          remotes::install_deps(".", dependencies = TRUE)
          devtools::install(".", upgrade = "never")
        shell: Rscript {0}

      - name: Install dependencies for checking
        run: |
          install.packages("testthat", type = "binary")
          install.packages("knitr", type = "binary")
          install.packages("rmarkdown", type = "binary")
          install.packages("devtools", type = "binary")
        shell: Rscript {0}

      - name: Check package
        run: |
          devtools::check(pkg = "R-package/")
        shell: Rscript {0}